version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - OPENAI_PROMPT_ID=${OPENAI_PROMPT_ID}
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_PROMPT_ID=${OPENAI_PROMPT_ID}
    restart: unless-stopped
    # Mount .env.local file if you have one
    env_file:
      - .env.local
    # Optional: volumes for development
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/.next
